### ISSUE TITLE
`System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.`

### ISSUE THREAD

**Issue by rakleed** [wiresock/WireSockUI#14]
I imported the config, but when I click on it or when I try to activate, I get this error every time. There is no such problem with TunnlTo.

<details><summary>Log:</summary>

```log
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at WireSockUI.Native.WireguardBoosterExports.wgb_create_tunnel_from_file_w(IntPtr wgboosterHandle, String fileName)
   at WireSockUI.WireSockManager.Connect(String profile)
   at WireSockUI.Forms.FrmMain.OnProfileClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
WireSockUI
    Assembly Version: 0.1.2.0
    Win32 Version: 0.1.2
    CodeBase: file:///C:/Program%20Files/WireSock%20VPN%20Client/wiresockui/WireSockUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

</details>

Windows 11 22H2, WireShock 1.2.26.1, WireShockUI 0.1.2.

**Comment by rakleed** [comment]
```config
[Interface]
PrivateKey = <private_key>
Address = 172.16.82.2/24
MTU = 
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = <public_key>
AllowedIPs = 172.16.82.1/32, 192.168.22.0/24, 0.0.0.0/0
Endpoint = <domain>:<port>
PersistentKeepalive = 5

AllowedApps = msedge
DisallowedApps = 
DisallowedIPs = 
```

**Comment by EntityinArray** [comment]
This issue just occurred for me:

From my limited googling, one way to solve this is could probably be to ditch AnyCPU and make separate x86 x64 builds

```
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.Runtime.InteropServices.SEHException (0x80004005): Внешний компонент создал исключение.
   в WireSockUI.Native.WireguardBoosterExports.wgb_create_tunnel_from_file_w(IntPtr wgboosterHandle, String fileName)
   в WireSockUI.WireSockManager.Connect(String profile)
   в WireSockUI.Forms.FrmMain.OnProfileClick(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
WireSockUI
    Версия сборки: 0.2.8.0
    Версия Win32: 0.2.8
    CodeBase: file:///C:/Users/dea/Downloads/WireSockUI-v0.2.8-AnyCPU-no-uwp/WireSockUI.exe
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4375.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.Resources.Extensions
    Версия сборки: 8.0.0.0
    Версия Win32: 8.0.23.53103
    CodeBase: file:///C:/Users/dea/Downloads/WireSockUI-v0.2.8-AnyCPU-no-uwp/System.Resources.Extensions.DLL
----------------------------------------
System.Memory
    Версия сборки: 4.0.1.2
    Версия Win32: 4.6.31308.01
    CodeBase: file:///C:/Users/dea/Downloads/WireSockUI-v0.2.8-AnyCPU-no-uwp/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Версия сборки: 4.0.4.1
    Версия Win32: 4.6.28619.01
    CodeBase: file:///C:/Users/dea/Downloads/WireSockUI-v0.2.8-AnyCPU-no-uwp/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Numerics.Vectors
    Версия сборки: 4.1.4.0
    Версия Win32: 4.6.26515.06
    CodeBase: file:///C:/Users/dea/Downloads/WireSockUI-v0.2.8-AnyCPU-no-uwp/System.Numerics.Vectors.DLL
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.

```

```
#
# WireGuard sample configuration, please provide the necessary details
#
; Local Interface Definition
[Interface]
PrivateKey = OHsw0/0...
; Local address in CIDR format
Address = 10.6.6.10/32
MTU = 1280
DNS = 1.0.0.1, 1.1.1.1

; Peer Definition
[Peer]
PublicKey = tiHI...
; Optional: preshared key
PresharedKey = 
; Peer IPv4, IPv6 or DNS endpoint with port
Endpoint = ... .su:4820
AllowedIPs = 0.0.0.0/0, ::/0
; Optional: Send persistent keep alive packets every 5 minutes (900 sec)
PersistentKeepalive = 900

; WireSock extensions

; SOCKS 5 Proxy to perform peer handshake
Socks5Proxy = ... .su:3860
Socks5ProxyUsername = ...
Socks5ProxyPassword = ...

```
