### ISSUE TITLE
Unable to find an entry point named 'wgb_create_tunnel_from_file_w' in the DLL 'wgbooster.dll'

### ISSUE THREAD

**Issue by f-liva** [wiresock/WireSockUI#82]
Occurs trying to run a tunnel file.

This are the error details:

```
Information on how to invoke JIT (Just-In-Time) debugging instead of this window 
is provided at the end of this message.

************** Exception Text **************
System.EntryPointNotFoundException: Unable to find an entry point named 'wgb_create_tunnel_from_file_w' in the DLL 'wgbooster.dll'.
   at WireSockUI.Native.WireguardBoosterExports.wgb_create_tunnel_from_file_w(IntPtr wgboosterHandle, String fileName)
   at WireSockUI.WireSockManager.Connect(String profile)
   at WireSockUI.Forms.FrmMain.OnProfileClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
WireSockUI
    Assembly Version: 0.2.8.0
    Win32 Version: 0.2.8
    CodeBase: file:///D:/Desktop/WireSockUI-v0.2.8-AnyCPU-no-uwp/WireSockUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.53103
    CodeBase: file:///D:/Desktop/WireSockUI-v0.2.8-AnyCPU-no-uwp/System.Resources.Extensions.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.2
    Win32 Version: 4.6.31308.01
    CodeBase: file:///D:/Desktop/WireSockUI-v0.2.8-AnyCPU-no-uwp/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.4.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///D:/Desktop/WireSockUI-v0.2.8-AnyCPU-no-uwp/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///D:/Desktop/WireSockUI-v0.2.8-AnyCPU-no-uwp/System.Numerics.Vectors.DLL
----------------------------------------
Microsoft.Win32.TaskScheduler
    Assembly Version: 2.10.1.0
    Win32 Version: 2.10.1.0
    CodeBase: file:///D:/Desktop/WireSockUI-v0.2.8-AnyCPU-no-uwp/Microsoft.Win32.TaskScheduler.DLL
----------------------------------------
mscorlib.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT Debugging **************
To enable JIT debugging, the value 
jitDebugging in the system.windows.forms section of the application’s or machine’s 
configuration file (machine.config) must be set.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exceptions 
will be sent to the JIT debugger registered on the computer,
rather than being handled by this dialog box.
```

**Comment by wiresock** [comment]
This report is from WireSockUI 0.2.8 paired with an older incompatible SDK export. Current releases are intended to run with the matching current WireSock Secure Connect CLI/SDK. Closing this obsolete compatibility report.
